name: ModFixNG
main: modfix.ModFixNG
version: 1.0
author: Shevchik
depend: [ProtocolLib]
load: STARTUP
commands:
  modfix:
    usage: 'Используйте команд /modfix help для получения списка комманд'