name: ModFixNG
main: modfixng.main.ModFixNG
version: 1.0
author: Shevchik
depend: [ProtocolLib]
load: STARTUP
commands:
  modfixng:
    aliases: modfix
    usage: 'Используйте команд /modfixng help для получения списка комманд'