name: ModFixNG
main: modfix.Main
version: 1.0
author: Shevchik
softdepend: [ProtocolLib]
load: STARTUP
commands:
  modfix:
    usage: 'Используйте команд /modfix help для получения списка комманд'